"""
Author : Rima Zinjuwadia

Task : This Python script calculates the occurrences of A, T, G, and C in a
multiline sequence, as well as the percentages of A, T, C, G, and CT.

Sequence Information : Homo sapiens ins gene, partial
GenBank: AJ009655.1
"""


#>AJ009655.1 Homo sapiens ins gene, partial 1393 bp FASTA
Seq ="""AGCAGGTCTGTTCCAAGGGCCTTTGCGTCAGGTGGGCTCAGGGTTCCAGGGTGGCTGGACCCCAGGCCCC
AGCTGTGCAGCAGGGAGGACGTGGCTGGGCTCGTGAAGCATGTGGGGGTGAGCCCAGGGGCCCCAAGGCA
GGGCACCTGGCCTTCAGCCTGCCTCAGCCCTGCCTGTCTCCCAGATCACTGTCCTTCTGCCATGGCCCTG
TGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGA
ACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGGCTTCTTCTA
CACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGGTGAGCCAACCGCCCATTGCTGCCCCTGGCCG
CCCCCAGCCACCCCCTGCTCCTGGCGCTCCCACCCAGCATGGGCAGAAGGGGGCAGGAGGCTGCCACCCA
GCAGGGGGTCAGGTGCACTTTTTTAAAAAGAAGTTCTCTTGGTCACGTCCTAAAAGTGACCAGCTCCCTG
TGGCCCAGTCAGAATCTCAGCCTGAGGACGGTGTTGGCTTCGGCAGCCCCGAGATACATCAGAGGGTGGG
CACGCTCCTCCCTCCACTCGCCCCTCAAACAAATGCCCCGCAGCCCATTTCTCCACCCTCATTTGATGAC
CGCAGATTCAAGTGTTTTGTTAAGTAAAGTCCTGGGTGACCTGGGGTCACAGGGTGCCCCACGCTGCCTG
CCTCTGGGCGAACACCCCATCACGCCCGGAGGAGGGCGTGGCTGCCTGCCTGAGTGGGCCAGACCCCTGT
CGCCAGCCTCACGGCAGCTCCATAGTCAGGAGATGGGGAAGATGCTGGGGACAGGCCCTGGGGAGAAGTA
CTGGGATCACCTGTTCAGGCTCCCACTGTGACGCTGCCCCGGGGCGGGGGAAGGAGGTGGGACATGTGGG
CGTTGGGGCCTGTAGGTCCACACCCAGTGTGGGTGACCCTCCCTCTAACCTGGGTCCAGCCCGGCTGGAG
ATGGGTGGGAGTGCGACCTAGGGCTGGCGGGCAGGCGGGCACTGTGTCTCCCTGACTGTGTCCTCCTGTG
TCCCTCTGCCTCGCCGCTGTTCCGGAACCTGCTCTGCGCGGCACGTCCTGGCAGTGGGGCAGGTGGAGCT
GGGCGGGGGCCCTGGTGCAGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCATT
GTGGAACAATGCTGTACCAGCATCTGCTCCCTCTACCAGCTGGAGAACTACTGCAACTAGACGCAGCCTG
CAGGCAGCCCCACACCCGCCGCCTCCTGCACCGAGAGAGATGGAATAAAGCCCTTGAACCAGC"""

#Converting multiline DNA seq to single line sequence

New_Seq=Seq.replace("\n","")

print(">AJ009655.1 Homo sapiens ins gene, partial",New_Seq)

#Counting Sequence Length
print("  ")
New_Seq_Len=len(New_Seq)
print("Length of Given Sequnce =",New_Seq_Len)

# A , T , G , C Total Number Count

A_Count=New_Seq.count("A")
T_Count=New_Seq.count("T")
G_Count=New_Seq.count("G")
C_Count=New_Seq.count("C")

print("Total Number of A =",A_Count)
print("Total Number of G =",G_Count)
print("Total Number of C =",C_Count)
print("Total Number of T =",T_Count)

# A% T% G% C% Count

A_Percent=(A_Count/New_Seq_Len)*100
T_Percent=(T_Count/New_Seq_Len)*100
G_Percent=(G_Count/New_Seq_Len)*100
C_Percent=(C_Count/New_Seq_Len)*100

print("Total Number of A% =",A_Percent)
print("Total Number of G% =",G_Percent)
print("Total Number of C% =",C_Percent)
print("Total Number of T% =",T_Percent)

# CT% Count

CT_Percent=(C_Count+T_Count)/(New_Seq_Len)*100

print("CT% =",CT_Percent)






